<?xml version="1.0" encoding="utf-8"?><Database Name="dubizzle" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=it-84;Initial Catalog=dubizzle;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dubizzleConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admins" Member="admins">
    <Type Name="admin">
      <Column Name="admin_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password_change_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ads" Member="ads">
    <Type Name="ad">
      <Column Name="ad_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="price_fixed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="subcat_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="location_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="condition" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="posted_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="posted_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="expire_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="contact_no" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="views" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="blocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="approved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ads_img" Member="ads_imgs">
    <Type Name="ads_img">
      <Column Name="ad_img_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ad_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.categories" Member="categories">
    <Type Name="category">
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="category_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="category_photo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="created_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modified_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.locations" Member="locations">
    <Type Name="location">
      <Column Name="location_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="location_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="location_photo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="created_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modified_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="user_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password_change_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="contact_no" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="last_active_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modified_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="blocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="activation_code" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ads_limit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="comments" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.web_config" Member="web_configs">
    <Type Name="web_config">
      <Column Name="config_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="config_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="config_val" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.User_GetSubCategories" Method="User_GetSubCategories">
    <Parameter Name="CATEGORY_ID" Parameter="cATEGORY_ID" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="User_GetSubCategoriesResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.User_GetSingleAdDetails" Method="User_GetSingleAdDetails">
    <ElementType Name="User_GetSingleAdDetailsResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TITLE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[DESC]" Member="DESC" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="PRICE" Type="System.String" DbType="VarChar(34)" CanBeNull="true" />
      <Column Name="CONDITION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CONTACT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOC" Type="System.String" DbType="VarChar(156)" CanBeNull="true" />
      <Column Name="POSTED_DATE" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="POSTED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VISITOR" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.User_GetMainPageData" Method="User_GetMainPageData">
    <ElementType Name="User_GetMainPageDataResult">
      <Column Name="CATEGORY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CATEGORY_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="C_COUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.User_GetLocations" Method="User_GetLocations">
    <ElementType Name="User_GetLocationsResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.User_GetCategories" Method="User_GetCategories">
    <ElementType Name="User_GetCategoriesResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.User_GetAdsList" Method="User_GetAdsList">
    <ElementType Name="User_GetAdsListResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TITLE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRICE" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CONDITION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CATEGORY" Type="System.String" DbType="VarChar(103)" CanBeNull="true" />
      <Column Name="LOCATION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="POSTED_DATE" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="VISITOR" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_GetSubCategories" Method="Admin_GetSubCategories">
    <ElementType Name="Admin_GetSubCategoriesResult">
      <Column Name="SR" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CATEGORY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SUB_CATEGORY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CATEGORY_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SUB_CATEGORY_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PHOTO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MODIFIED_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_GetLocations" Method="Admin_GetLocations">
    <ElementType Name="Admin_GetLocationsResult">
      <Column Name="SR" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PHOTO_URL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MODIFIED_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_GetCategories" Method="Admin_GetCategories">
    <ElementType Name="Admin_GetCategoriesResult">
      <Column Name="SR" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CATEGORY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CATEGORY_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PHOTO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MODIFIED_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_VerifyUser" Method="Admin_VerifyUser">
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RETURN_CODE" Parameter="rETURN_CODE" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>